// <auto-generated />
using Lab3_OOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab3_OOP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240426090332_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Lab3_OOP.Models.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Human");
                });

            modelBuilder.Entity("Lab3_OOP.Models.Klempner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gehalt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("INN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenschID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenschID");

                    b.ToTable("Klempner");
                });

            modelBuilder.Entity("Lab3_OOP.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HumanID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Studak")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HumanID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Lab3_OOP.Models.Klempner", b =>
                {
                    b.HasOne("Lab3_OOP.Models.Human", "Mensch")
                        .WithMany()
                        .HasForeignKey("MenschID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensch");
                });

            modelBuilder.Entity("Lab3_OOP.Models.Student", b =>
                {
                    b.HasOne("Lab3_OOP.Models.Human", "Human")
                        .WithMany()
                        .HasForeignKey("HumanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Human");
                });
#pragma warning restore 612, 618
        }
    }
}
